server:
  port: 8080
  servlet:
    context-path: /courtstar
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courtstarv5
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1099077344805-af8jknff9pfv2hfvffu3b521p1sgdja0.apps.googleusercontent.com
            client-secret: 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

jwt:
  signerKey: "OpLoSIHROWo8482Fsk63QXj/jNb95u9Xl2ZZyUDKQwN687kCVo5FVVFBdbQfcqXJ"
