server:
  port: 8080
  servlet:
    context-path: /courtstar
spring:
  datasource:
    url: jdbc:sqlserver://courtstarv2.database.windows.net:1433;database=courtstar;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: adminv2
    password: Aa@123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mail:
    host: smtp.gmail.com
    port: 587
    username: minhoan305@gmail.com
    password: jfcr heji pmzn bmzu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      encoding: UTF-8
      cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1099077344805-af8jknff9pfv2hfvffu3b521p1sgdja0.apps.googleusercontent.com
            client-secret: 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

jwt:
  signerKey: "OpLoSIHROWo8482Fsk63QXj/jNb95u9Xl2ZZyUDKQwN687kCVo5FVVFBdbQfcqXJ"
  valid-duration: 3600
  refreshable-duration: 36000
