server:
  port: 8080
  servlet:
    context-path: /courtstar
spring:
  datasource:
    url: jdbc:sqlserver://courtstar.database.windows.net:1433;database=CourtStar;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
    username: csadmin
    password: courtstar123@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1099077344805-af8jknff9pfv2hfvffu3b521p1sgdja0.apps.googleusercontent.com
            client-secret: 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

jwt:
  signerKey: "OpLoSIHROWo8482Fsk63QXj/jNb95u9Xl2ZZyUDKQwN687kCVo5FVVFBdbQfcqXJ"
